apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-restrict-ingress
  namespace: app-prod
spec:
  podSelector:
    matchLabels:
      app: web
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              owner: platform
      ports:
        - protocol: TCP
          port: 80
